// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>


const char THING_ID[]           = "dfe9c21c-ecd9-4b09-a85f-9b807deea304";
const char DEVICE_LOGIN_NAME[]  = "e126918d-4769-45f4-bf07-7e79b3279eff";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onRightChange();
void onDownChange();
void onUpChange();
void onLeftChange();
void onNumChange();


bool right;
bool down;
bool up;
bool left;
int num;



void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.setThingId(THING_ID);
  ArduinoCloud.addProperty(right, READWRITE, ON_CHANGE, onRightChange);
  ArduinoCloud.addProperty(down, READWRITE, ON_CHANGE, onDownChange);
  ArduinoCloud.addProperty(up, READWRITE, ON_CHANGE, onUpChange);
  ArduinoCloud.addProperty(left, READWRITE, ON_CHANGE, onLeftChange);
  ArduinoCloud.addProperty(num, READWRITE, ON_CHANGE, onNumChange);
}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
